@startuml

interface ProveedorMeteorologico {
    + obtenerDato() : Dato
}

class WeatherApiAdapter implements ProveedorMeteorologico {
    + obtenerDato() : Dato
}

class SistemaClimalert {
    - historialClimas : List<Dato>
    - alertasProgramadas : List<Alerta>
    + registrarAlerta(Alerta) : void
    + registrarYEvaluarClima(Dato) : List<Alerta>
}

Record Dato {
    - temperatura : double
    - humedad : double
    - ubicacion : String
    - fechaHora : LocalDateTime
}

interface Alerta {
    + evaluarCondiciones(Dato) : boolean
    + obtenerMensajeDeAdvertencia(Dato) : String
}

class AlertaTemperatura implements Alerta {
    - umbralTemperatura : double
    + evaluarCondiciones(Dato) : boolean
    + obtenerMensajeDeAdvertencia(Dato) : String
}

class AlertaHumedad implements Alerta {
    - umbralHumedad : double
    + evaluarCondiciones(Dato) : boolean
    + obtenerMensajeDeAdvertencia(Dato) : String
}

enum OperadorLogico {
    AND
    OR
}

class AlertaCompuesta implements Alerta {
    - alertas : List<Alerta>
    - operador : OperadorLogico
    + evaluarCondiciones(Dato) : boolean
    + obtenerMensajeDeAdvertencia(Dato) : String
}

Record Notificacion {
    - detalle : Dato
    - destinatario : String
    - mensaje : String
}

interface NotificadorPort {
    + armarNotificacion(Dato, String, String) : Notificacion
    + despachar(Notificacion) : void
}

class NotificadorEmail implements NotificadorPort {
    + armarNotificacion(Dato, String, String) : Notificacion
    + despachar(Notificacion) : void
}

class ClimalertApplicationService {
    - proveedorMeteorologico : ProveedorMeteorologico
    - notificadorEmail : NotificadorPort
    - destinatariosAlerta : List<String>
    + procesarMonitoreoClimatico(SistemaClimalert) : void
}

ProveedorMeteorologico -> Dato
NotificadorPort -> Notificacion
SistemaClimalert -> "*" Dato
SistemaClimalert -> "*" Alerta
AlertaCompuesta -> "*" Alerta
AlertaCompuesta -> OperadorLogico
ClimalertApplicationService -> ProveedorMeteorologico
ClimalertApplicationService -> NotificadorPort
Alerta ..> Dato

@enduml