@startuml

interface ProveedorMeteorologico{
    + obtenerDato() : Dato
}

class WeatherApiAdapter implements ProveedorMeteorologico{
    + obtenerDato() : Dato
}

class SistemaClimalert{
    - datoClimaActual : Dato
    - historialDeClimas : <Dato>
    - proveedor : ProveedorMeteorologico
    - alertasProgramadas : <Alerta>

    + obtenerDato() : Dato
}

Record Dato{
    - temperatura : double
    - humedad : double
    - ubicacion : String
    - fechaHora : LocalDateTime
}

class Alerta{
    + evaluarCondiciones(Dato) : Bool
}

class AlertaTemperaturaHumedadAltas implements Alerta{
    + evaluarCondiciones(Dato) : Bool
}

Record Notificacion{
    - detalle : Dato
    - destinatario : String
}

class NotificadorEmail{
    + armarNotificacion(Dato) : Notificacion
    + despachar(Notificacion) : void
}

ProveedorMeteorologico -> Dato
NotificadorEmail -> Notificacion
SistemaClimalert -> "*"Dato
SistemaClimalert -> ProveedorMeteorologico
SistemaClimalert -> "*" Alerta
Alerta ..> Dato

@enduml